name: Update Version and Upload Python Package

on:
  push:
    tags:
      - 'v*'

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      # Check out das Repository
      - name: Check out code
        uses: actions/checkout@v3

      # Python einrichten
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Abhängigkeiten installieren
      - name: Install dependencies
        run: |
          pip install toml

      # Versionsnummer in pyproject.toml und setup.py aktualisieren
      - name: Update version in pyproject.toml and setup.py
        run: |
          TAG_NAME=${GITHUB_REF##*/}
          VERSION=${TAG_NAME#v}
          echo "Updating version to $VERSION"
          python update_version.py $VERSION

      # Erstelle das Paket und lade es hoch
      - name: Build and Upload package
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          pip install build twine
          python -m build
          twine upload dist/*
